### ISSUE TITLE
Merge into official project

### ISSUE THREAD

**Issue by dmsnell** [dtolnay/dissimilar#1]
Hi @dtolnay - cool port! I was wondering if you considered requesting to merge this into [google/diff-match-patch](https://github.com/google/diff-match-patch). That project has been moved to GitHub and incorporates implementations in other languages already too.

I found your repo while trying to understand how best to handle encoding issues with the original library (it has problems handling surrogate pairs / non-word-boundaries) and I thought your implementation would sit well in the official one, might even be fun comparing a compiled version of it in WebAssembly to the JS implementation.

**Comment by dtolnay** [comment]
The code is appropriately licensed such that they can take a fork, but it isn't something that I will be able to dedicate time to.
