### ISSUE TITLE
Incompatibility with the original alogrithm

### ISSUE THREAD

**Issue by andelf** [dtolnay/dissimilar#19]
Cannot generated the same result as the original speedtest [google/diff-match-patch](https://github.com/google/diff-match-patch).

Note:

- speedtest should return 2187 diffs, I use the python3 version
- this crate: 313,  applied Semantic diff post proc
- [dmp](https://docs.rs/dmp/0.1.2/dmp/) generates the same result
- [diff_match_patch](https://docs.rs/diff_match_patch/0.1.1/diff_match_patch/) cannot generate the same result: 2177

**Comment by andelf** [comment]
Close. This should be a feature request for timeout and post proc options.

**Comment by dtolnay** [comment]
The Rust `dissimilar::diff(text1, text2)` is equivalent to the following from the python3 API:

```python
dmp = diff_match_patch()
dmp.Diff_Timeout = 0.0
diffs = dmp.diff_main(text1, text2)
dmp.diff_cleanupSemantic(diffs)
```

which both produce 313.

Without `diff_cleanupSemantic` the python3 implementation produces a low-quality diff. That's why you saw so many chunks come out of it (2187).

**Comment by andelf** [comment]
@dtolnay Thanks for your clarification.
