### ISSUE TITLE
Consider implementing `serde::Serialize` and `serde::Deserialize` for `Chunk`?

### ISSUE THREAD

**Issue by teymour-aldridge** [dtolnay/dissimilar#3]
I'm trying to use `dissimilar` in my web application, but I've run into trouble because `Serialize` and `Deserialize` are not implemented for `Chunk`. I think this would be useful, even if it were placed behind a feature flag (e.g. `serde` like Chrono).

I'd be happy to submit a pull request to make this (small) change.

**Comment by dtolnay** [comment]
I think I would prefer not to do this. I would recommend translating the chunks to and from a type defined by your crate and putting the Serialize and Deserialize impl on that type.

**Comment by teymour-aldridge** [comment]
Yeah, that's what I've gone for.

Thanks for writing this library!
